### ISSUE TITLE
Add Futurelearn course data

### ISSUE THREAD

**Issue by Atyanar** [mammooc/mammooc.org#124]
As a user I want to have courses from [Futurelearn](https://www.futurelearn.com/) on mammooc. Therefore add a course worker for Futurelearn.
They do not provide an API, but have a look at: 
https://github.com/dhawalhshah/class-central/tree/master/src/ClassCentral/ScraperBundle/Scraper

Since they do not provide an API, it is not possible to get user data from Futurelearn.

**Comment by rosabraatz** [comment]
Instead of the API use the json feed: https://www.futurelearn.com/feeds/courses
