### ISSUE TITLE
Additional user account connections

### ISSUE THREAD

**Issue by Atyanar** [mammooc/mammooc.org#128]
- [ ] coursera
 - [Coursera FAQ](https://s3.amazonaws.com/coursera_assets/app+platform/coursera_app_platform_faq.html)
 - [Coursera Presentation](https://s3.amazonaws.com/coursera_assets/app+platform/Coursera+App+Platform+-+Conference+Tech+Session.pdf)
- [ ] edx
- [ ] Iversity

**Comment by rosabraatz** [comment]
move to new issues #127 #122 #123
