### ISSUE TITLE
Deadlines of courses

### ISSUE THREAD

**Issue by Atyanar** [mammooc/mammooc.org#268]
As a user, I want to have an overview of all deadlines of my courses. Especially if I am enrolled in more than one course by more than one provider it is difficult to keep track of all courses.
Therefore, mammooc can collect all relevant dates and show them for instance on the user’s dashboard. Moreover, I want to receive an email reminder if a deadline is nearly reached (Ref: #247).
Interesting or important dates:
- [ ] deadlines for assignments
- [ ] dates for final exams
- [ ] start dates of bookmarked, recommended or obligatory courses

For providing an overview of all dates, mammooc has to collect the related data from the providers. Currently this data is not processed although some providers make them available.

**Comment by MrSerth** [comment]
For some providers, we now support these dates. As soon as a bookmarked course starts, we send a reminder via emails. Other dates are available via a ICS calendar feed and currently no further emails are planned.
