### ISSUE TITLE
Add universities to datamodel and get them from providers

### ISSUE THREAD

**Issue by Atyanar** [mammooc/mammooc.org#303]
Most provider have partners who create the courses. Partners are mostly universities, like Stanford or MIT. As a user I want to know which university offers the course. Therefore collect the corresponding data from MOOC providers and change the data model accordingly. Most of the data is currently available with the provided API but not saved.

Think about filtering/searching and choose a data model that also represents the channels by openHPI / openSAP (#254). So choose a good generic name.

These changes of the data model could also be uses to represent the openHPI/openSAP channels. So choose a good generic name.

**Comment by rosabraatz** [comment]
I think the concept of partners for a MOOC is represented by 'organisations' in the data model. The concept of integrating channels to the data model is not yet implemented, but there exists a corresponding issue: #254 Therefore I would close this issue. @MrSerth, what do you think?

**Comment by MrSerth** [comment]
You're right and currently, we are already using the `organizations` table to store this information (unfortunately with some duplicates). I agree to close this issue.
