### ISSUE TITLE
User Testing

### ISSUE THREAD

**Issue by mandyklingbeil** [mammooc/mammooc.org#341]
User Testing with a high fidelity prototype

Prepare a prototype based on our current dev, adding features and workflows hard-coded

**Comment by rosabraatz** [comment]
@mandyklingbeil What is about this issue? Are you still working on it? If not please close this issue, otherwise please assign yourself. :)

**Comment by MrSerth** [comment]
Assuming that work for this is finished. Please let me know, if this is not the case.

**Comment by mandyklingbeil** [comment]
Yes, I finished this issue in August. Thanks for closing :)
