### ISSUE TITLE
[BUG] Course overview buttons in firefox

### ISSUE THREAD

**Issue by rosabraatz** [mammooc/mammooc.org#494]
In Firefox the buttons 'bookmark'  and 'enroll' are not displayed right. They are always white buttons even if I bookmarked a course. 
![bug_kursuebersicht_buttons](https://cloud.githubusercontent.com/assets/7458390/8853365/8b324bc0-315a-11e5-819f-8eac8e2bfcc2.png)

**Comment by MrSerth** [comment]
Problem fixed in newer versions of Firefox. Closing.
