### ISSUE TITLE
recommendation course completion on create token

### ISSUE THREAD

**Issue by rosabraatz** [mammooc/mammooc.org#499]
In recommendation/obligatory recommendation form: It should only be possible to create token which are in autocompletion, otherwise no recommendation will be created, but the user receives a notification about a successfull creation.
For the autocomplete of users and groups it is already implemented that you can only create tokens which are in the autocompletion.
It should be implemented as well for the autocompletion of courses. This is a bit more tricky because you have to send ajax requests to controller.

**Comment by MrSerth** [comment]
Done.
