### ISSUE TITLE
Change EdX Course Worker from Yahoo Pipe to EdX API

### ISSUE THREAD

**Issue by sebastiankliem** [mammooc/mammooc.org#509]
Yahoo Pipes will no longer be available in September 2015! Currently the edX course worker uses the Yahoo Pipes to get data from edX. edX supports an API, therefore change the edX course worker to the edX API.

**Comment by rosabraatz** [comment]
edX API does not support information about courses (yet). Therefore use course feed (https://www.edx.org/api/v2/report/course-feed/rss or https://www.edx.org/api/report/course-feed/export)

**Comment by MrSerth** [comment]
There is a course structure API offered by edX, which is currently experimental (therefore listed as v0): http://edx.readthedocs.org/projects/edx-platform-api/en/latest/course_structure/index.html

**Comment by rosabraatz** [comment]
Please have a more detailed look: 'Currently the Course Structure API is for internal use only; third parties cannot use the API to access course structure data.'

**Comment by MrSerth** [comment]
Yes, you're right. It is for internal use only since quite a while (I remember it was so at the end of June when I first say this API being developed) and I hope this will change soon. Please excuse for any inconvenience.

**Comment by MrSerth** [comment]
Done with #596
