### ISSUE TITLE
Edit recommendation messages

### ISSUE THREAD

**Issue by mandyklingbeil** [mammooc/mammooc.org#568]
As a user I want to be able to edit my messages I wrote when recommending a course to someone else.

**Comment by MrSerth** [comment]
@mandyklingbeil Is this issue a duplicate to #318, where users should have the possibility to edit recommendations?

**Comment by mandyklingbeil** [comment]
@MrSerth Yes, we already spoke about the possibility of editing and delete recommendations, that's right. I must have overlooked that one. :) Thanks!
