### ISSUE TITLE
Automatic mails with new courses once per day

### ISSUE THREAD

**Issue by jprberlin** [mammooc/mammooc.org#584]
As a user it would be nice if i can opt in and receive a mail  with new courses every day.

**Comment by MrSerth** [comment]
I think, a new message every day might be too much information. What about an individual setting so that the user can decide, when he wants to get these mails? Possible settings might be: every day, once a week, every two weeks, once a month

**Comment by jprberlin** [comment]
even nicer.

**Comment by jprberlin** [comment]
Idea: Have some basic filters, for example only german courses ...
