### ISSUE TITLE
view completion of courses

### ISSUE THREAD

**Issue by rosabraatz** [mammooc/mammooc.org#62]
The superior should have the possibility to get an overview of an employee's completed courses from different MOOC providers. The completion of a course could be represented by a record of achievement, certificate, etc.

- complete course (prio 1)
- certificate (pdf, link) upload manual (prio 2)
- certificate (pdf, link) get automatically (prio 2)

**Comment by rosabraatz** [comment]
@MrSerth: already done?

**Comment by MrSerth** [comment]
I moved the remaining work to #535 and #536
