### ISSUE TITLE
Check newsletter interval validation

### ISSUE THREAD

**Issue by MrSerth** [mammooc/mammooc.org#707]
We should revalidate, whether our newsletter interval is working correctly. I selected to get my newsletter every day and as you see in my inbox, I got a mail every two days.

<img width="456" alt="bildschirmfoto 2016-07-22 um 09 59 30" src="https://cloud.githubusercontent.com/assets/7300329/17050462/46277af6-4ff3-11e6-9237-b3f550955d76.png">

**Comment by rosabraatz** [comment]
@MrSerth this issue is already closed with your PR, right?

**Comment by MrSerth** [comment]
Yes, it's done.
