### ISSUE TITLE
Containerized application fills disk with log files

### ISSUE THREAD

**Issue by jgraichen** [mammooc/mammooc.org#778]
The containerized application still write log files to e.g. `log/production.log` that quickly fill up the whole disk and can only be fixed by restarting the container.

As a containerized application it should not write files but output logs to stdout. This way the container engine (e.g. docker) can properly store and manage (e.g. rotate) the logs from the application.

**Comment by MrSerth** [comment]
I added the parameter `RAILS_LOG_TO_STDOUT` (which is already present and correctly configured in `production.rb`) to prevent writing the log files. In addition to the code changes, I also modified the server's `docker-compose.yml` to reflect the changes.
