### ISSUE TITLE
Checkbox not in line with text on registration page

### ISSUE THREAD

**Issue by georgberecz** [mammooc/mammooc.org#80]
On the [registration page](https://mammooc.org/users/sign_up) the checkbox and the text for accepting the terms and conditions of mammooc are not inline:

![image](https://cloud.githubusercontent.com/assets/7314829/6663660/2b5ea032-cbc9-11e4-9aa8-eb0fe2fa1d96.png)

**Comment by MrSerth** [comment]
We removed the check box, so that the alignment is no problem any longer,
